"""
PDF report generation module
"""
from reportlab.lib.pagesizes import letter, A4
from reportlab.lib import colors
from reportlab.lib.units import inch
from reportlab.platypus import SimpleDocTemplate, Table, TableStyle, Paragraph, Spacer, PageBreak
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.enums import TA_CENTER, TA_RIGHT
from io import BytesIO
from datetime import datetime


def generate_monthly_report(user, monthly_kwh, bill_details, consumption_logs):
    """Generate PDF monthly report"""
    buffer = BytesIO()
    doc = SimpleDocTemplate(buffer, pagesize=A4)
    elements = []
    styles = getSampleStyleSheet()
    
    # Title
    title_style = ParagraphStyle(
        'CustomTitle',
        parent=styles['Heading1'],
        fontSize=24,
        textColor=colors.HexColor('#2c3e50'),
        spaceAfter=30,
        alignment=TA_CENTER
    )
    
    elements.append(Paragraph("EnergyTrack Monthly Report", title_style))
    elements.append(Spacer(1, 0.2*inch))
    
    # User Info
    user_info = [
        ['Report Date:', datetime.now().strftime('%B %d, %Y')],
        ['User Name:', user.name],
        ['Email:', user.email],
        ['Report Period:', datetime.now().strftime('%B %Y')]
    ]
    
    user_table = Table(user_info, colWidths=[2*inch, 4*inch])
    user_table.setStyle(TableStyle([
        ('FONTNAME', (0, 0), (-1, -1), 'Helvetica'),
        ('FONTSIZE', (0, 0), (-1, -1), 10),
        ('TEXTCOLOR', (0, 0), (0, -1), colors.HexColor('#34495e')),
        ('FONTNAME', (0, 0), (0, -1), 'Helvetica-Bold'),
        ('BOTTOMPADDING', (0, 0), (-1, -1), 12),
    ]))
    
    elements.append(user_table)
    elements.append(Spacer(1, 0.3*inch))
    
    # Consumption Summary
    elements.append(Paragraph("Consumption Summary", styles['Heading2']))
    elements.append(Spacer(1, 0.1*inch))
    
    summary_data = [
        ['Metric', 'Value'],
        ['Total Consumption', f"{monthly_kwh:.2f} kWh"],
        ['Average Daily Usage', f"{monthly_kwh / 30:.2f} kWh"],
        ['Peak Power Recorded', f"{max([log.global_active_power for log in consumption_logs]):.2f} kW" if consumption_logs else "N/A"],
        ['Number of Readings', str(len(consumption_logs))]
    ]
    
    summary_table = Table(summary_data, colWidths=[3*inch, 2*inch])
    summary_table.setStyle(TableStyle([
        ('BACKGROUND', (0, 0), (-1, 0), colors.HexColor('#3498db')),
        ('TEXTCOLOR', (0, 0), (-1, 0), colors.whitesmoke),
        ('ALIGN', (0, 0), (-1, -1), 'LEFT'),
        ('FONTNAME', (0, 0), (-1, 0), 'Helvetica-Bold'),
        ('FONTSIZE', (0, 0), (-1, 0), 12),
        ('BOTTOMPADDING', (0, 0), (-1, 0), 12),
        ('BACKGROUND', (0, 1), (-1, -1), colors.beige),
        ('GRID', (0, 0), (-1, -1), 1, colors.black),
        ('FONTNAME', (0, 1), (-1, -1), 'Helvetica'),
        ('FONTSIZE', (0, 1), (-1, -1), 10),
    ]))
    
    elements.append(summary_table)
    elements.append(Spacer(1, 0.3*inch))
    
    # Billing Details
    elements.append(Paragraph("Billing Breakdown", styles['Heading2']))
    elements.append(Spacer(1, 0.1*inch))
    
    billing_data = [['Description', 'Units/Amount', 'Rate', 'Cost (Rs.)']]
    billing_data.append(['Fixed Charges', '-', '-', f"{bill_details['fixed_charges']:.2f}"])
    
    for slab in bill_details['breakdown']:
        billing_data.append([
            slab['slab'],
            f"{slab['units']:.2f}",
            f"Rs.{slab['rate']:.2f}",
            f"Rs.{slab['cost']:.2f}"
        ])
    
    billing_data.append(['', '', 'Total:', f"Rs.{bill_details['total_cost']:.2f}"])
    
    billing_table = Table(billing_data, colWidths=[2.5*inch, 1.5*inch, 1*inch, 1.5*inch])
    billing_table.setStyle(TableStyle([
        ('BACKGROUND', (0, 0), (-1, 0), colors.HexColor('#27ae60')),
        ('TEXTCOLOR', (0, 0), (-1, 0), colors.whitesmoke),
        ('ALIGN', (0, 0), (-1, -1), 'CENTER'),
        ('FONTNAME', (0, 0), (-1, 0), 'Helvetica-Bold'),
        ('FONTSIZE', (0, 0), (-1, 0), 11),
        ('BOTTOMPADDING', (0, 0), (-1, 0), 12),
        ('BACKGROUND', (0, 1), (-1, -2), colors.lightgrey),
        ('GRID', (0, 0), (-1, -1), 1, colors.black),
        ('FONTNAME', (0, -1), (-1, -1), 'Helvetica-Bold'),
        ('FONTSIZE', (0, -1), (-1, -1), 12),
        ('BACKGROUND', (0, -1), (-1, -1), colors.HexColor('#f39c12')),
    ]))
    
    elements.append(billing_table)
    elements.append(Spacer(1, 0.3*inch))
    
    # Footer
    footer_style = ParagraphStyle(
        'Footer',
        parent=styles['Normal'],
        fontSize=9,
        textColor=colors.grey,
        alignment=TA_CENTER
    )
    
    elements.append(Spacer(1, 0.5*inch))
    elements.append(Paragraph("Generated by EnergyTrack - Smart Energy Monitoring System", footer_style))
    elements.append(Paragraph(f"Report generated on {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}", footer_style))
    
    # Build PDF
    doc.build(elements)
    buffer.seek(0)
    return buffer
